### ISSUE TITLE
Im getting a syntax error since the last Chrome update

### ISSUE THREAD

**Issue by natbrood** [KoffeinFlummi/alientube#28] opened 2019-03-31 10:13 UTC
You broke reddit :(
`SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at Request.onSuccess (chrome-extension://nnkpagjmddndhnkiecjecfknleggbhfo/js/script.js:2566:47) at HttpRequest.<anonymous> (chrome-extension://nnkpagjmddndhnkiecjecfknleggbhfo/js/script.js:367:29)`

I'm running Version 73.0.3683.86 (Official Build) (64-bit) on W10.
I am logged in on reddit.

**Comment by MatthewSerinity** [comment] 2019-03-31 16:51
Also having this issue

**Comment by Aphataeros** [comment] 2019-03-31 21:00
Same on OSX in chrome.

**Comment by alstoc** [comment] 2019-04-01 12:17
Happens to me too on Windows 10 in Chrome. Worked perfectly until a few weeks ago and since then it's broken.

**Comment by Hawke-Esq** [comment] 2019-04-02 09:00
Yep same happening here too.

**Comment by whisperingsage** [comment] 2019-04-07 00:24
When this issue happens, the button to switch back to default youtube comments disappears as well.

**Comment by gozzarda** [comment] 2019-04-09 17:35
This is being caused by Chrome's introduction of Cross-Origin Read Blocking (CORB) as detailed here: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

The link above offers a fix that involves proxying cross-origin requests through the extension's background page, sending messages between the background and content scripts to relay the data.

Hope this info helps. I am sorry to say I lack the time and the experience with TypeScript to do anything about this myself in the forseeable future.

**Comment by mastahype** [comment] 2019-04-09 17:52
This is a dupe of #25 and was rolled out in Chrome 73 on March 12. Since @gozzarda posted the Chromium tracker link, some of us might take a stab at fixing it. It doesn't look terribly difficult on the surface, but I'm not an extension developer so it could require extensive changes.

**Closed as completed** 2019-04-12 22:44 UTC
