### ISSUE TITLE
Alientube not working when logged in to reddit

### ISSUE THREAD

**Issue by victorhartman** [KoffeinFlummi/alientube#26] opened 2019-03-14 16:33 UTC
As the title says. The comments don't load when I'm logged in to reddit. I get the following error message:

You broke Reddit :(
SyntaxError: Unexpected end of JSON input at JSON.parse ( &lt;anonymous&gt; ) at Request.onSuccess (chrome-extension://egkobojmnpcpcfhnhiagjacimhgfhgdk/js/script.js:2567:47) at HttpRequest.<anonymous> (chrome-extension://egkobojmnpcpcfhnhiagjacimhgfhgdk/js/script.js:367:29)

To fix it: I go to reddit, log out, refresh youtube page.

Maybe caused by an API change by Reddit?

**Comment by pmauldin** [comment] 2019-03-19 23:10
I found the source of the problem here: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

Chrome rolled out an update on March 12th. Seems like the issue can be fixed by just making the XHR request in the background script?

**Comment by victorhartman** [comment] 2019-03-20 12:31
It seems you are right. This is the error in the console.

script.js:385 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://api.reddit.com/search.json?q=(url:3DJtUAAXe_0VI%20OR%20url:JtUAAXe_0VI)%20(site:youtube.com%20OR%20site:youtu.be) with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Which is this line.
https://github.com/KoffeinFlummi/alientube/blob/1ecdf4971c7ff2efe1e80b2ee103477e9c0121c6/TypeScript/HttpRequest.ts#L74

Unfortunately i'm unfamiliar with this. I hope someone can fix it.

**Comment by Wizek** [comment] 2019-03-27 07:43
Same issue here.

`
SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at Request.onSuccess (chrome-extension://nnkpagjmddndhnkiecjecfknleggbhfo/js/script.js:2566:47) at HttpRequest.<anonymous> (chrome-extension://nnkpagjmddndhnkiecjecfknleggbhfo/js/script.js:367:29)
`

**Comment by MitchRuns** [comment] 2019-03-27 21:57
This used to happen infrequently but is now happening with every single video. I am getting the same error as above.

**Comment by iamafk** [comment] 2019-03-29 17:39
I'm having the same problem. Signing out of reddit fixes it. Any solution?

**Comment by nightkall** [comment] 2019-04-06 09:59
Same problem here, I signed out and now it's working.

**Comment by mastahype** [comment] 2019-04-09 17:51
_If_ this is related to CORB, this is a dupe of #25 and was rolled out in Chrome 73 on March 12. Since @gozzarda posted the Chromium link, some of us might take a stab at fixing it.

**Closed as completed** 2019-04-12 22:44 UTC
